#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get update
sudo apt-get install -y haproxy
sudo sed -i 's|ENABLED=0|ENABLED=1|' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo sed -i '$s|$|\n\nlisten appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 54159-web-01 3.89.155.134:80 check\n\tserver 54159-web-02 3.85.41.196:80 check|' /etc/haproxy/haproxy.cfg
sudo service haproxy start
